name: deployment

on:
  push:
    branches:
      - master
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: image
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_ref }}

      - name: Login Git-job registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deployment
        run: |
          docker pull ${{ steps.image.outputs.lowercase }}
          docker stack deploy -c ./deploy/docker-compose.${{ steps.vars.outputs.short_ref }}.yml --with-registry-auth ${{ steps.vars.outputs.short_ref }}_moon


